# Generated by Django 2.1 on 2019-01-27 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmodel',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major_name', to='profiles.MajorModel'),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_name', to='profiles.SchoolModel'),
        ),
    ]
