# Generated by Django 2.1 on 2018-09-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180924_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='services_completed',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
