# Generated by Django 2.1 on 2018-09-26 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_auto_20180925_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkmodel',
            name='profile',
        ),
        migrations.AddField(
            model_name='linkmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL),
        ),
    ]
