# Generated by Django 2.1 on 2018-09-26 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20180926_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
