# Generated by Django 2.1 on 2018-10-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20181003_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_pic',
            field=models.FileField(default='tc.png', upload_to='profile_pics'),
        ),
    ]
