# Generated by Django 2.1 on 2018-10-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20181009_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_pic',
            field=models.ImageField(default='tc.png', upload_to='profile_pics'),
        ),
    ]
