# Generated by Django 2.1 on 2018-10-26 19:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20181009_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='educationmodel',
            name='school_name',
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='status',
            field=models.CharField(choices=[('ONG', 'Ongoing'), ('INC', 'Incomplete'), ('COM', 'Complete')], default='Howard', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.SchoolModel'),
        ),
    ]
