# Generated by Django 2.1 on 2018-11-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20181026_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picturemodel',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='PictureModel',
        ),
    ]
