# Generated by Django 2.1 on 2018-10-01 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180924_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='is_parent',
            field=models.BooleanField(default=False, verbose_name='is a parent category'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='services.CategoryModel'),
        ),
    ]
