# Generated by Django 2.1 on 2019-03-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190310_1848'),
        ('services', '0002_auto_20190310_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='skills',
            field=models.ManyToManyField(blank=True, to='profiles.SkillModel'),
        ),
    ]
