# Generated by Django 2.1 on 2019-02-03 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190202_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='servicepicturemodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_photos', to='services.ServiceModel'),
        ),
    ]
