# Generated by Django 2.1 on 2019-03-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_jobmodel_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='category',
            new_name='categories',
        ),
    ]
