# Generated by Django 2.1 on 2019-02-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190203_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
