# Generated by Django 2.1 on 2019-03-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190311_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicemodel',
            old_name='category',
            new_name='categories',
        ),
    ]
