# Generated by Django 2.1 on 2019-02-15 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20190205_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepicturemodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='services.ServiceModel'),
        ),
    ]
