# Generated by Django 2.1 on 2018-11-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20181117_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='description',
            field=models.TextField(default='okay', max_length=500),
            preserve_default=False,
        ),
    ]
