# Generated by Django 2.1 on 2019-02-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20190215_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='service', to='services.CategoryModel'),
        ),
    ]
