# Generated by Django 2.1 on 2018-11-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicemodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='review',
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='review',
            field=models.ManyToManyField(related_name='reviews', to='services.ReviewModel'),
        ),
    ]
