# Generated by Django 2.1 on 2018-11-18 00:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20181117_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='buyer',
            field=models.ManyToManyField(blank=True, related_name='buyers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='review',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='services.ReviewModel'),
        ),
    ]
