# Generated by Django 2.1 on 2019-02-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20190216_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='delivery_time',
            field=models.CharField(choices=[('early', '1-3'), ('normal', '3-5'), ('later', '7+')], default='normal', max_length=8),
        ),
    ]
