# Generated by Django 2.1 on 2019-02-18 04:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_servicemodel_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
