# Generated by Django 2.1 on 2018-11-18 01:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20181117_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='review',
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='service',
            field=models.ForeignKey(default=uuid.UUID('75879119-5a6c-4e46-b08d-5400859d6b06'), on_delete=django.db.models.deletion.CASCADE, to='services.ServiceModel'),
        ),
    ]
