# Generated by Django 2.1 on 2018-11-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20181117_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='categories', to='services.CategoryModel'),
        ),
    ]
