# Generated by Django 2.1 on 2019-02-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20190222_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='delivery_time',
            field=models.CharField(choices=[('Early', '1-3'), ('Normal', '3-5'), ('Later', '7+')], default='Normal', max_length=20),
        ),
    ]
