# Generated by Django 2.1 on 2018-11-18 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20181117_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.ServiceModel'),
        ),
    ]
