# Generated by Django 2.1 on 2019-02-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190201_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='services', to='services.ServiceModel'),
        ),
    ]
