# Generated by Django 2.1 on 2019-02-02 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190201_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrymodel',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='orders.CartModel'),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.ServiceModel'),
        ),
    ]
