# Generated by Django 2.1 on 2019-02-03 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190201_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrymodel',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_entries', to='orders.ServiceOrderModel'),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_entries', to='orders.CartModel'),
        ),
        migrations.AlterField(
            model_name='entrymodel',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_entries', to='services.ServiceModel'),
        ),
    ]
