# Generated by Django 2.1 on 2019-02-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_historicalserviceordermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceordermodel',
            name='service',
        ),
    ]
