# Generated by Django 2.1 on 2019-02-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_serviceordermodel_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrymodel',
            name='isOrdered',
            field=models.BooleanField(default=False),
        ),
    ]
