# Generated by Django 2.1 on 2019-02-03 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_entrymodel_isordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrymodel',
            old_name='isOrdered',
            new_name='is_ordered',
        ),
    ]
