# Generated by Django 2.1 on 2019-02-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190202_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalserviceordermodel',
            name='status',
            field=models.CharField(choices=[('ORD', 'Ordered'), ('INP', 'In Progress'), ('INC', 'Incomplete'), ('REF', 'Refunded'), ('COM', 'Complete')], default='INP', max_length=3),
        ),
        migrations.AlterField(
            model_name='serviceordermodel',
            name='status',
            field=models.CharField(choices=[('ORD', 'Ordered'), ('INP', 'In Progress'), ('INC', 'Incomplete'), ('REF', 'Refunded'), ('COM', 'Complete')], default='INP', max_length=3),
        ),
    ]
