# Generated by Django 2.1 on 2019-02-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20190203_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrymodel',
            name='status',
            field=models.CharField(blank=True, choices=[('ORD', 'Ordered'), ('INP', 'In Progress'), ('INC', 'Incomplete'), ('REF', 'Refunded'), ('COM', 'Complete')], max_length=3, null=True),
        ),
    ]
