# Generated by Django 2.1 on 2019-02-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_entrymodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrymodel',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
