# Generated by Django 2.1 on 2019-02-05 00:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_entrymodel_is_delivered'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(max_length=1000)),
                ('is_valid_complaint', models.BooleanField(default=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.EntryModel')),
            ],
        ),
    ]
