# Generated by Django 2.1 on 2019-02-06 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20190205_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmodel',
            name='entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='orders.EntryModel'),
        ),
    ]
